### PR TITLE
fix: fix design of survey question select elements

### LINKED ISSUE #1065: Low contrast text is difficult to read and does not meet accessibility standards
The org I volunteer with uses spoke to run text banks, and I regularly see people struggle with the low contrast grey text on grey backgrounds.  The "current question" dropdown is the hardest for new folks, especially if they have any kind of visual impairment.  Using firefox's built in accessibility tools I was able to determine that the text in question has a contrast ratio well below the WCAG recommendation (see screenshot below).

Screen Shot 2022-02-08 at 4 23 18 PM

### PR DESCRIPTION
**Pull request by bchrobot**
## Description

Update the select component to Material UI v4 to fix a11y issues.

## Motivation and Context

The v0 select element is very hard to read in this context.

Fixes #1065 

## How Has This Been Tested?

This has been tested locally.

## Screenshots (if appropriate):

<table>
<tr>
<td></td>
<td>Before fix</td>
<td>After fix</td>
</tr>

<tr>
<td>W/o answer</td>
<td>

Notification_Center

</td>
<td>

Screen Shot 2022-02-25 at 8 38 23 AM

</td>
</tr>

<tr>
<td>W/ answer</td>
<td>

Notification_Center

</td>
<td>

Screen Shot 2022-02-25 at 8 38 56 AM

</td>
</tr>

</table>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation Changes

N/A

## Checklist:

- [x] My code follows the code style of this project.
- [x] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

**Review by ajohn25 — CHANGES_REQUESTED** [review]
Comments from @kohlee @emonson4:
1. Expand survey options selector to fill screen as in previous screenshot.
2. Add space between "expand question" and question headings.
3. Larger/Clearer caret click target in the survey options drop down.

**Review by ninabaldwin — CHANGES_REQUESTED** [review]
Since one of the requestors was concerned about ADA compliancy, can we darken the "Your message" section just a little bit (shown in both fixed images) so that it's within ADA compliancy, but also looks greyed out?

**Comment by ajohn25** [comment]
> 2. Add space between "expand question" and question headings.

Talking and writing at the same time failed me. This should've said add vertical space between the "Current question" heading and the question text, as in the before fix screenshot. 

155724806-16684f0e-f6fb-4108-99bd-9119eb3c2fab

**Review by ajohn25 — APPROVED** [review]

**Review by ninabaldwin — CHANGES_REQUESTED** [review]
Regarding the "Your Message," I think it has been made too dark now. Here is what I am thinking:
your message

**Comment by ninabaldwin** [comment]
> > You can use this hex code B4B4B4
> 
> I am unable to easily edit this text color 😔
> 
> The new color is provided by the Material UI design system. Once we have fully migrated from Material UI v0 to Material UI v4 (partially completed) we can Spoke styling as a whole but until then I would rather not introduce more exceptions to the design system.

Got it! sounds good. One other note though. It looks like the send button is not aligned with the other buttons. Can that be fixed?

**Review by ninabaldwin — APPROVED** [review]
Alignment looks good! Thank you @bchrobot!

**Pull request merged**
